apiVersion: v1
kind: Namespace
metadata:
  name: dns-test
---
apiVersion: v1
kind: Pod
metadata:
  name: test1
  namespace: dns-test
  labels:
    app: test
spec:
  containers:
  - image: centos:8
    name: test1
    command: ["/bin/bash", "-c", "echo 'I am TEST 1'; sleep 3000"]
---
apiVersion: v1
kind: Pod
metadata:
  name: test2
  namespace: dns-test
  labels:
    app: test
spec:
  containers:
  - image: centos:8
    name: test2
    command: ["/bin/bash", "-c", "echo 'I am TEST 1'; sleep 3000"]
---
apiVersion: v1
kind: Service
metadata:
  name: test-svc
  namespace: dns-test
spec:
  type: ClusterIP
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
