apiVersion: v1
kind: Pod
metadata:
  name: test3
  namespace: dns-test
  labels:
    app: test
spec:
  containers:
  - image: centos:8
    name: test3
    command: ["/bin/bash", "-c", "echo 'I am TEST 1'; sleep 3000"]
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
    searches:
      - ns1.svc.cluster-domain.example
      - my.dns.search.suffix
    options:
      - name: ndots
        value: "2"
      - name: edns0

