apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: pod1
spec:
  containers:
  - image: gcr.io/jetstack-workshops/demo:v1
    name: pod1
    command: ["/bin/bash", "-c", "echo 'I am Pod 1'; sleep 3000"]

 
