apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: pod2
spec:
  containers:
  - image: gcr.io/jetstack-workshops/demo:v1
    name: pod2
    command: ["/bin/bash", "-c", "echo 'I am Pod 2'; sleep 3000"]