apiVersion: v1
kind: Pod
metadata:
  name: pod3
  namespace: test
  labels:
    app: pod3
spec:
  containers:
  - image: gcr.io/jetstack-workshops/demo:v1
    name: pod3
    command: ["/bin/bash", "-c", "echo 'I am Pod 3'; sleep 3000"]

 
