apiVersion: v1
kind: Pod
metadata:
  name: livenessprobe-pod
  labels:
    app: demo
spec:
  containers:
  - image: gcr.io/jetstack-workshops/kuard-amd64:blue 
    name: demo
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        port: 8080
        path: /healthy
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3 # Default
      successThreshold: 1 # Default
      timeoutSeconds: 1   # Default
---
apiVersion: v1
kind: Service
metadata:
  name: liveness-svc
spec:
  type: NodePort
  selector:
    app: demo
  ports:
  - port: 8080
    targetPort: 8080
