apiVersion: v1
kind: Pod
metadata:
  name: poststart-pod
  labels:
    app: demo
spec:
  containers:
  - image: gcr.io/jetstack-workshops/kuard-amd64:blue 
    name: demo
    ports:
    - containerPort: 8080
    lifecycle:
      postStart:
        exec:
          command:
          - sh
          - -c
          - "sleep 30"
---
apiVersion: v1
kind: Service
metadata:
  name: readiness-svc
spec:
  type: NodePort
  selector:
    app: demo
  ports:
  - port: 8080
    targetPort: 8080
