apiVersion: v1
kind: Pod
metadata:
  name: probe-demo
  labels:
    app: demo
spec:
  containers:
  - image: gcr.io/jetstack-workshops/sample-web:sleep30
    name: slow-app
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 2
      failureThreshold: 3 # Default
      successThreshold: 1 # Default
      timeoutSeconds: 1   # Default
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 2
      failureThreshold: 3 # Default
      successThreshold: 1 # Default
      timeoutSeconds: 5   # Default 1
    startupProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 30
      successThreshold: 1 # Default
      timeoutSeconds: 1   # Default
