apiVersion: v1
kind: Service
metadata:
  name: deployment-svc
spec:
  type: ClusterIP
  selector:
    app: deployment-demo
  ports:
    - port: 80
      name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  labels:
    app: deployment-demo
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxSurge: 100%
     maxUnavailable: 0%
  replicas: 3
  selector:
    matchLabels:
      app: deployment-demo
  template:
    metadata:
      labels:
        app: deployment-demo
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8

