apiVersion: v1
kind: Service
metadata:
  name: statefulset-svc
  labels:
    app: statefulset
spec:
  selector:
    app: statefulset-demo
  ports:
  - port: 80
    name: web
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-demo
spec:
  selector:
    matchLabels:
      app: statefulset-demo # has to match .spec.template.metadata.labels
  serviceName: "statefulset-svc"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: statefulset-demo # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.9
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
