apiVersion: v1
kind: Pod
metadata:
  name: centos-pod
  labels:
    app: test
spec:
  containers:
  - image: centos:8 
    name: test1
    command: ["/bin/bash", "-c", "echo 'I am TEST 1'; sleep 3000"]